// Pull the handful of icons the HUD actually uses out of the game-icons set and
// write them into src/icons.js as raw SVG paths.
//
// The full set is 4134 icons; shipping it would dwarf the rest of the bundle, and
// tree-shaking cannot help because the lookups are by name at runtime. So the
// dependency stays a devDependency and this script bakes the chosen dozen-odd
// into a generated module that is committed alongside the source.
//
//   node scripts/icons.mjs
//
// Icons are from game-icons.net by Lorc, Delapouite and contributors, CC BY 3.0.
// Every one below was checked for legibility at 16px on the HUD's dark ground —
// several obvious-sounding choices (thermometer-hot, missile-swarm, crystal-cluster,
// jet-fighter) turn to mush at that size and were rejected for the ones here.

import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

/** Semantic name in the game → icon name in the set. */
const WANTED = {
  speed: 'speedometer',
  alt: 'airplane-departure',
  boost: 'afterburn',
  heat: 'small-fire',
  hull: 'shield',
  score: 'laurels',
  pickup: 'crystal-shine',
  kill: 'explosion-rays',
  primary: 'laser-burst',
  secondary: 'torpedo',
  ability: 'aura',
  time: 'stopwatch',
  gate: 'finish-line',
  lock: 'convergence-target',
  rival: 'light-fighter',
  scan: 'radar-sweep',
  // on-screen control deck
  brake: 'parachute',        // a drag chute is exactly what an airbrake does
  cam: 'binoculars',
  gyro: 'gyroscope',
  throttle: 'lever',
  pause: 'pause-button',
};

const set = JSON.parse(readFileSync(require.resolve('@iconify-json/game-icons/icons.json'), 'utf8'));
const box = `0 0 ${set.width ?? 512} ${set.height ?? 512}`;

const missing = Object.values(WANTED).filter((n) => !set.icons[n]);
if (missing.length) {
  console.error(`icons: not in the set — ${missing.join(', ')}`);
  process.exit(1);
}

const entries = Object.entries(WANTED).map(([key, name]) => {
  // fill="currentColor" is already on every path; strip it and let CSS own the
  // colour so a single .ico rule can tint by state.
  const body = set.icons[name].body.replaceAll(' fill="currentColor"', '');
  return `  // ${name}\n  ${key}: '${body.replaceAll("'", "\\'")}',`;
});

const out = `// GENERATED by scripts/icons.mjs — do not edit by hand.
//
// Icons from game-icons.net by Lorc, Delapouite and contributors, licensed
// CC BY 3.0: https://github.com/game-icons/icons
//
// Chosen for legibility at 16px against the HUD's dark ground, which rules out
// most of the busier candidates in that set. Add one by editing the WANTED map in
// scripts/icons.mjs and re-running it.

const BOX = '${box}';

export const ICON = {
${entries.join('\n')}
};

/**
 * Inline SVG sized in \`em\`, so an icon scales with whatever text it sits beside
 * and inherits its colour. Unknown names render nothing rather than throwing —
 * a missing glyph must never take a HUD frame down.
 */
export function icon(name, cls = '') {
  const body = ICON[name];
  if (!body) return '';
  return \`<svg class="ico\${cls ? ' ' + cls : ''}" viewBox="\${BOX}" aria-hidden="true">\${body}</svg>\`;
}
`;

writeFileSync(new URL('../src/icons.js', import.meta.url), out);
const kb = (Buffer.byteLength(out) / 1024).toFixed(1);
console.log(`icons: ${entries.length} baked into src/icons.js (${kb} kB)`);
