// Flavour lines for passing pilots in Chill mode. Uniformly warm, deliberately
// varied in register — some chatty, some clipped radio-speak, some odd.

export const CALLSIGNS = [
  'BLUE HERON', 'TIN KETTLE', 'MARGUERITE', 'SLOW SUNDAY', 'OKAPI',
  'CANDLEWICK', 'NINE OF CUPS', 'PALE HORSE', 'MOTH', 'JUNIPER',
  'SALT FLATS', 'HALF PAST', 'CORMORANT', 'LITTLE OWL', 'DRIFTWOOD',
  'CLEMENTINE', 'FAR MERIDIAN', 'POSTCARD', 'GOOSE', 'AMBERGRIS',
];

export const GREETINGS = [
  "Hey there! I'm going this way — want to fly together for a bit?",
  'Nice hull. Mind if I pace you a while?',
  "Beautiful light out here today, isn't it.",
  'Wing on me if you like. No hurry either way.',
  "Didn't expect company this far out. Good surprise.",
  'You fly like someone who knows the long way round.',
  'Plenty of sky. Take whatever you need of it.',
  'Heading nowhere in particular. Best kind of heading.',
  'Nice line through that valley back there.',
  'Hey. Just saying hello, nothing more than that.',
  'Good afternoon out here. Or morning. Hard to say.',
  'Fly safe out there. And slow, if you can manage it.',
  "That's a lovely paint job. Really.",
  'I have been out here three hours and it keeps getting better.',
  'Cutting west at the ridge. Come along if it suits.',
  'Steady as she goes, friend.',
  'You are the first thing I have seen move in an hour. Welcome.',
  'Some days the sky is just generous.',
  'No cargo, no schedule, no complaints.',
  'Hey! Watch the thermals off that ridge, they are lovely.',
  'Room for two on this heading.',
  'You looked like you were enjoying yourself. Thought I would say so.',
  'Clear skies. Keep them.',
  'I have got coffee and nowhere to be. Good day.',
  'Wave if you pass again. I will be around.',
  'Do you ever just stop and hover? Try it sometime.',
  'Good bones on that ship. Flies like it means it.',
  'Just drifting. Recommend it highly.',
  'Hello from the slow lane.',
  'You are welcome alongside any time.',
  'Careful of the cloud deck ahead, it is thicker than it looks.',
  'Genuinely nice to see another light out here.',
  'Take the scenic route. It is all scenic.',
  'Not lost. Just unhurried.',
  'That was a clean turn. Respect.',
  'Hey, you. Yes, you. Nice flying.',
  'I named this cloud. You can name the next one.',
  'Following the light west. You?',
  'No destination, no disappointment.',
  'Say hello to the coast for me.',
  'Been meaning to fly this route for years. Worth it.',
  'You are doing fine. Just so you know.',
  'Wind is kind today. Make the most of it.',
  'Company is optional out here. So is loneliness.',
  'I will peel off at the next range. Was good sharing the air.',
  'Whatever you are running from, it is not out here.',
  'Pretty ship. Prettier sky.',
  'Slow down. It does not go anywhere.',
  'Signal is clear, sky is open, all is well.',
  'Safe travels, whichever way you end up going.',
];
